# Copyright 2019 The Kubernetes Authors.

# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at

# http://www.apache.org/licenses/LICENSE-2.0

# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
- name: Define file modes
  set_fact:
    last_log_mode: "0664"
    machine_id_mode: "0444"

- name: Disable swap service and ensure it is masked
  systemd:
    name: temp-disk-swapfile
    enabled: false
    masked: true
  when: ansible_memory_mb.swap.total != 0

- name: Remove SUSE subscription
  block:
    - name: Non cloud managed subscription
      block:
        - name: Remove subscriptions
          command: SUSEConnect --de-register
      when: "packer_builder_type not in ['amazon']"
    - name: AWS managed subscription
      block:
        - name: Remove subscriptions
          command: registercloudguest --clean
      when: packer_builder_type == "amazon"
    - name: Remove SUSECOnnect folders
      file:
        state: absent
        path:
          - /etc/SUSEConnect
          - /etc/zypp/credentials.d/*
          - /etc/zypp/repos.d/*
          - /etc/zypp/services.d/*
  when: ansible_distribution == "sles"

- name: Remove zypper package cache
  command: zypper clean -a

- name: Reset network interface IDs
  shell: sed -i '/^\(HWADDR\|UUID\)=/d' /etc/sysconfig/network/ifcfg-*
