---
- name: create kubelet systemd directory
  file:
    path: "/etc/systemd/system/kubelet.service.d/"
    state: directory
  notify:
    - reload systemd

- name: copy containerd kubelet systemd drop-in to remote
  template:
    src: "kubelet-drop-in.conf"
    dest: "/etc/systemd/system/kubelet.service.d/0-containerd.conf"
  notify:
    - restart containerd

- name: copy crictl config to remote
  template:
    src: "crictl.yaml"
    dest: "/etc/crictl.yaml"

- name: create containerd directory
  file:
    path: "/etc/containerd/"
    state: directory

- name: create containerd imports directory
  file:
    path: "/etc/containerd/conf.d"
    state: directory

- name: copy default configuration to remote
  template:
    src: "config.toml.tmpl"
    dest: "/etc/containerd/config.toml"
  notify:
    - restart containerd
