---
- hosts: all
  name: Prepare Ansible - Flatcar Python setup
  become: true
  gather_facts: false
  tasks:
    - name: Flatcar no update
      changed_when: false
      script: ../packer/files/no-update-flatcar.sh
    - name: exec bootstrap python
      changed_when: false
      script: ../packer/files/bootstrap-flatcar.sh
    - name: check for flatcar python
      raw: stat /opt/bin/.bootstrapped
      changed_when: false
      failed_when: false
      register: flatcar_bootstrapped
    - name: change python if bootstrapped
      set_fact:
        ansible_python_interpreter: /opt/bin/python
      when: flatcar_bootstrapped.rc == 0
- hosts: all
  name: Provision
  become: true
  # TODO: hack to pass vars easily for now
  pre_tasks:
    - include_vars: vars/centos/centos-7.yaml
      when: ansible_os_family == "RedHat"
    - include_vars: vars/flatcar/flatcar.yaml
      when: ansible_os_family == "Flatcar"
  roles:
    - role: packages
    - role: gpu
    - role: config
    - role: networking
    - role: providers
    - role: images
      when: download_images
    - role: sysprep
      when: sysprep # make the finalize process skipable
  environment: "{{ default_env }}"
