---
name: Lint

# yamllint disable-line rule:truthy
on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  super-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Checkout konvoy-image-builder repository
        uses: actions/checkout@v3

      - name: Set environment Variables from Dotenv
        uses: c-py/action-dotenv-to-setenv@v4
        with:
          env-file: .github/super-linter.env

      - name: Run Super-Linter
        uses: github/super-linter@v4.9.7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NOTE(jkoelker) super-linter is broken for go packages
          #                https://github.com/github/super-linter/issues/143
          VALIDATE_GO: false
          # NOTE(jongiddy) super-linter is broken for Packer HCL files
          #                https://github.com/github/super-linter/pull/1707
          # This can be removed when a release > 4.2.2 exists.
          VALIDATE_TERRAGRUNT: false
          # we don't need a _pedantic_ natural language linter
          VALIDATE_NATURAL_LANGUAGE: false
          # we use terraform to provision *test* infrastructure that is deleted
          VALIDATE_TERRAFORM_TFLINT: false
  golangci-lint:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout konvoy-image-builder repository
          uses: actions/checkout@v3

        - name: Setup Go
          uses: actions/setup-go@v3
          with:
            go-version-file: 'go.mod'
            cache: true

        - name: Run golangci lint
          uses: golangci/golangci-lint-action@v3
          with:
            #version of golangci-lint to use with
            version: latest
