---
name: Lint

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4

      - name: Environment Variables from Dotenv
        uses: c-py/action-dotenv-to-setenv@v3
        with:
          env-file: .github/super-linter.env

      - name: Run Super-Linter
        uses: github/super-linter@v4.9.0
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # NOTE(jkoelker) super-linter is broken for go packages
          #                https://github.com/github/super-linter/issues/143
          VALIDATE_GO: false
          # NOTE(jongiddy) super-linter is broken for Packer HCL files
          #                https://github.com/github/super-linter/pull/1707
          # This can be removed when a release > 4.2.2 exists.
          VALIDATE_TERRAGRUNT: false

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.1.0
