---
"on":
  push:
    branches:
      - main

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release-please.outputs.release_created }}
      release_tag_name: ${{ steps.release-please.outputs.tag_name }}
      release_upload_url: ${{ steps.release-please.outputs.upload_url }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release-please
        with:
          release-type: go
          package-name: konvoy-image-builder
          changelog-types: >-
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"chore","section":"Miscellaneous","hidden":true}
            ]

      - if: ${{ steps.release-please.outputs.release_created }}
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - if: ${{ steps.release-please.outputs.release_created }}
        name: Snapshot
        run: make devkit.run
        env:
          WHAT: make build.snapshot

      - if: ${{ steps.release-please.outputs.release_created }}
        name: Docker Login
        uses: docker/login-action@v2
        with:
          registry: docker.io
          username: mesosphereci
          password: ${{ secrets.DOCKER_PASS }}

      - if: ${{ steps.release-please.outputs.release_created }}
        name: Release
        run: make devkit.run
        env:
          DOCKER_CLI_EXPERIMENTAL: "enabled"
          GITHUB_TOKEN: ${{ secrets.MESOSPHERECI_USER_TOKEN }}
          WHAT: make release
  bump-kib:
    needs: release-please
    runs-on: ubuntu-latest
    steps:
      - if: ${{ needs.release-please.outputs.release_created }}
        name: Setup Go
        uses: actions/setup-go@v3
        with:
           go-version: '1.17.0'

      - if: ${{ needs.release-please.outputs.release_created }}
        name: Fetch CAPPP
        uses: actions/checkout@v3
        with:
          repository: mesosphere/cluster-api-provider-preprovisioned
          token: ${{ secrets.MESOSPHERECI_USER_TOKEN }}
          path: cluster-api-provider-preprovisioned
          fetch-depth: 0

      - if: ${{ needs.release-please.outputs.release_created }}
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"

      - if: ${{ needs.release-please.outputs.release_created }}
        name: Update KIB in CAPPP
        run: make update-kib
        working-directory: cluster-api-provider-preprovisioned
        env:
          GITHUB_TOKEN: ${{ secrets.MESOSPHERECI_USER_TOKEN }}

      - if: ${{ needs.release-please.outputs.release_created }}
        name: Create Pull Request for KIB bump in CAPPP
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.MESOSPHERECI_USER_TOKEN }}
          add-paths: preprovisioned/kib
          body: bumps KIB to latest version
          commit-message: "feat: bump kib to ${{ needs.release-please.outputs.release_tag_name }}"
          path: cluster-api-provider-preprovisioned
          title: "feat: bump kib to ${{ needs.release-please.outputs.release_tag_name }}"

  sign-binary:
    runs-on: macos-latest
    needs: release-please
    env:
      KEYCHAIN: job-${{ github.job }}-${{ github.run_id }}-${{ github.run_number }}-${{ github.run_attempt }}
    steps:
      - if: ${{ needs.release-please.outputs.release_created }}
        uses: dsaltares/fetch-gh-release-asset@1.0.0
        with:
          version: "tags/${{ needs.release-plese.outputs.release_tag_name }}"
          file: "konvoy-image-bundle-${{ needs.release-plese.outputs.release_tag_name }}_darwin_amd64.tar.gz"

      - if: ${{ needs.release-please.outputs.release_created }}
        name: Create directory to extract the pulled file into
        run: mkdir "konvoy-image-bundle_darwin_amd64"

      - if: ${{ needs.release-please.outputs.release_created }}
        name: Extract the pulled file
        run: tar -xvzf "konvoy-image-bundle-${{ needs.release-plese.outputs.release_tag_name }}_darwin_amd64.tar.gz" -C "konvoy-image-bundle_darwin_amd64"

      - if: ${{ needs.release-please.outputs.release_created }}
        name: Remove original downloaded file
        run: rm "konvoy-image-bundle-${{ needs.release-plese.outputs.release_tag_name }}_darwin_amd64.tar.gz"


      - if: ${{ needs.release-please.outputs.release_created }}
        name: Fetch current main directory
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - if: ${{ needs.release-please.outputs.release_created }}
        name: Import Code-Signing Certificates
        uses: Apple-Actions/import-codesign-certs@v1
        with:
          keychain: ${{ env.KEYCHAIN }}
          # The certificates in a PKCS12 file encoded as a base64 string
          p12-file-base64: ${{ secrets.D2IQ_APPLE_DEVELOPER_CERTIFICATE_P12_BASE64 }}
          # The password used to import the PKCS12 file.
          p12-password: ${{ secrets.D2IQ_APPLE_DEVELOPER_CERTIFICATE_PASSWORD }}

      - if: ${{ needs.release-please.outputs.release_created }}
        name: Install required binaries
        run: |
          brew tap mitchellh/gon
          brew install mitchellh/gon/gon

      - if: ${{ needs.release-please.outputs.release_created }}
        name: Run Gon to notarize
        env:
          GITHUB_TOKEN: ${{ secrets.MESOSPHERECI_USER_TOKEN }}
          AC_USERNAME: ${{ secrets.D2IQ_APPLE_DEVELOPER_USERNAME }}
          AC_PASSWORD: ${{ secrets.D2IQ_APPLE_DEVELOPER_PASSWORD }}
        run: gon ./gon.hcl -log-level=info -log-json ./config.hcl

      - if: ${{ needs.release-please.outputs.release_created }}
        name: Tar signed bundle
        run: tar czf konvoy-image-bundle-${{ needs.release-plese.outputs.release_tag_name }}_darwin_amd64.tar.gz konvoy-image-bundle_darwin_amd64

      - name: Delete keychain
        if: ${{ needs.release-please.outputs.release_created }}
        run: |
          security delete-keychain "${{ env.KEYCHAIN }}".keychain

      - if: ${{ needs.release-please.outputs.release_created }}
        name: Get checksum file
        uses: dsaltares/fetch-gh-release-asset@1.0.0
        with:
          version: "tags/${{ needs.release-plese.outputs.release_tag_name }}"
          file: "*_checksums.txt"

      - name: Calculate checksum
        if: ${{ needs.release-please.outputs.release_created }}
        run: |
          cat *checksums.txt | grep darwin | xargs -I{} sed -i'' s/{}//g *checksums.txt
          sed -i'' '/^[[:space:]]*$/d'*checksums.txt
          sha256sum konvoy-image-bundle-${{ needs.release-plese.outputs.release_tag_name }}_darwin_amd64.tar.gz >> *checksums.txt


      - if: ${{ needs.release-please.outputs.release_created }}
        name: Replace release artifact
        uses: ncipollo/release-action@v1
        with:
          tag: "tags/${{ needs.release-plese.outputs.release_tag_name }}"
          artifacts: konvoy-image-bundle-${{ needs.release-plese.outputs.release_tag_name }}_darwin_amd64.tar.gz,*checksums.txt
          replacesArtifacts: true
          token: ${{ secrets.MESOSPHERECI_USER_TOKEN }}
          artifactErrorsFailBuild: true
